// User metrics aggregated from all data sources
export interface UserMetrics {
  /** Digital landscape: elevation, terrain, places */
  landscape?: {
    elevation?: number;
    elevationPath?: number[];
    lat?: number;
    lng?: number;
    placeTypes?: string[];
    nearbyPlaces?: string[];
  };
  spotify?: {
    isPlaying?: boolean;
    tempo?: number;
    trackName?: string;
    artistName?: string;
  };
  /** Uploaded playlist (JSON with tracks array) */
  uploadedPlaylist?: { tracks: { name?: string; tempo?: number }[] };
  digitalUsage?: {
    screenTimeHours?: number;
    appCategories?: string[];
  };
  /** Pipeline output: news, themes, weather */
  news?: {
    headlines: string[];
    categories?: Record<string, string[]>;
    dominantThemes?: string[];
  };
  weather?: {
    temp: number;
    condition: string;
    humidity?: number;
  };
}

// Game types (expanded for decision tree)
export type GameType =
  | 'endless_runner'
  | 'obstacle_dodge'
  | 'rhythm_tap'
  | 'memory_match'
  | 'trivia'
  | 'reaction_test';

// Game config generated by Gemini
export interface GameConfig {
  gameType: GameType;
  reasoning?: string;
  config: {
    scrollSpeed?: number;
    obstacleDensity?: number;
    terrainHeights?: number[];
    theme?: 'day' | 'night';
    difficulty?: number;
    [key: string]: unknown;
  };
}
