// User metrics aggregated from all data sources
export interface UserMetrics {
  /** Digital landscape: elevation, terrain, places */
  landscape?: {
    elevation?: number;
    elevationPath?: number[];
    lat?: number;
    lng?: number;
    placeTypes?: string[];
    nearbyPlaces?: string[];
  };
  spotify?: {
    isPlaying?: boolean;
    tempo?: number;
    trackName?: string;
    artistName?: string;
  };
  digitalUsage?: {
    screenTimeHours?: number;
    appCategories?: string[];
  };
  /** Pipeline output: news, themes, weather */
  news?: {
    headlines: string[];
    categories?: Record<string, string[]>;
    dominantThemes?: string[];
  };
  weather?: {
    temp: number;
    condition: string;
    humidity?: number;
  };
}

// Game config generated by Gemini
export interface GameConfig {
  gameType: 'endless_runner' | 'obstacle_dodge' | 'rhythm_tap';
  reasoning?: string;
  config: {
    scrollSpeed?: number;
    obstacleDensity?: number;
    terrainHeights?: number[];
    theme?: 'day' | 'night';
    difficulty?: number;
    [key: string]: unknown;
  };
}
