// User metrics aggregated from all data sources
export interface UserMetrics {
  /** Digital landscape: elevation, terrain, places */
  landscape?: {
    elevation?: number;
    elevationPath?: number[];
    lat?: number;
    lng?: number;
    placeTypes?: string[];
    /** Actual place names for location-specific tasks (e.g. "Bryant Park", "Blue Bottle Coffee") */
    nearbyPlaces?: { name: string; types?: string[] }[];
  };
  spotify?: {
    isPlaying?: boolean;
    tempo?: number;
    trackName?: string;
    artistName?: string;
  };
  /** Uploaded playlist (JSON with tracks array) */
  uploadedPlaylist?: { tracks: { name?: string; tempo?: number }[] };
  digitalUsage?: {
    screenTimeHours?: number;
    appCategories?: string[];
  };
  /** Pipeline output: news, themes, weather */
  news?: {
    headlines: string[];
    categories?: Record<string, string[]>;
    dominantThemes?: string[];
  };
  weather?: {
    temp: number;
    condition: string;
    humidity?: number;
  };
}

// Game type: real-world tasks only, verified via image upload + Gemini
export type GameType = 'real_world_task';

// Game config generated by Gemini (real-world task only)
export interface GameConfig {
  gameType: 'real_world_task';
  reasoning?: string;
  config: {
    task: string;
    verificationCriteria: string;
    travelItinerary?: string;
    sideQuest?: string;
    theme?: 'day' | 'night';
    flavor?: string;
    mood?: string;
    [key: string]: unknown;
  };
}
